name: flutter_application_3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons8-search.svg
    - assets/three-dots-svgrepo-com.svg
    - assets/clock-svgrepo-com (1).svg
    - assets/instagram-tag-icon.svg
